apiVersion: v1
kind: Service
metadata:
  labels:
    name: todos
  name: todos
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: todos
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos
spec:
  selector:
    matchLabels:
      app: todos
  replicas: 1
  template:
    metadata:
      labels:
        app: todos
    spec:
      containers:
      - name: todos
        image: harbor.tanzuworld.com/openso/todos-tbs:latest
        ports:
        - containerPort: 8080
